version: "3.0.8"
services:
  mysqldb:
    image: mysql:latest
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: department_db
      MYSQL_USER: ediaz
      MYSQL_PASSWORD: ediaz
      MYSQL_ROOT_PASSWORD: root
